# Latest stable production tag
# Run as non-root for production
FROM thehiveproject/thehive:5.3.5  
ENV CASSANDRA_CLUSTER_NAME=TheHive
COPY config/application.conf /etc/thehive/application.conf
USER thehive  
