apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencti
  namespace: openrisk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: opencti
  template:
    metadata:
      labels:
        app: opencti
    spec:
      containers:
        - name: opencti
          image: opencti/platform:latest
          env:
            - name: REDIS_URL
              value: redis://redis:6379
            - name: ES_URL
              value: http://elasticsearch:9200
            - name: MINIO_ENDPOINT
              value: minio:9000
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: openrisk-secrets
                  key: MINIO_ROOT_USER
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: openrisk-secrets
                  key: MINIO_ROOT_PASSWORD
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080