apiVersion: apps/v1
kind: Deployment
metadata:
  name: openrmf-web
  namespace: openrisk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: openrmf-web
  template:
    metadata:
      labels:
        app: openrmf-web
    spec:
      containers:
        - name: openrmf-web
          image: cingulara/openrmf-web:latest
          env:
            - name: JWTAUTHORITY
              value: http://openrmf-keycloak:8080/realms/openrmf
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: openrisk-secrets
                  key: MONGO_URI
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080