apiVersion: v1
kind: Secret
metadata:
  name: openriskops-secrets
  namespace: openriskops
type: Opaque
stringData:
  MONGO_URI: mongodb://mongo:27017/openrmf
  POSTGRES_PASSWORD: password
  # Add all .env keys