apiVersion: v1
kind: Secret
metadata:
  name: openrisk-secrets
  namespace: openrisk
type: Opaque
stringData:
  MONGO_URI: mongodb://mongo:27017/openrmf
  POSTGRES_PASSWORD: password
  # Add all .env keys